# Generated by Django 4.1.3 on 2022-11-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageStenography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='media/toBeEncrypted', verbose_name='Bild'),
        ),
    ]
