# Generated by Django 4.1.3 on 2022-11-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageStenography', '0002_alter_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='encrypted',
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='toBeEncrypted', verbose_name='Bild'),
        ),
    ]
